# Generated by Django 5.1.6 on 2025-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_address_order_phone_order_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide',
            name='usage_instruction',
            field=models.TextField(default='Usage instructions not available yet.'),
            preserve_default=False,
        ),
    ]
